import {
  Siren,
  House,
  Scissors,
  Monitor,
  GraduationCap,
  Car,
  PartyPopper,
  Paintbrush,
  BrickWall,
  Layers,
  PanelTop,
  Flower2,
  Bug,
  Smartphone,
  Laptop,
  Wifi,
  Hand,
  Palette,
  Heart,
  BookOpen,
  Languages,
  Music,
  Dumbbell,
  Wrench,
  Truck,
  Droplets,
  BatteryCharging,
  Camera,
  Disc3,
  UtensilsCrossed,
  Gift,
} from 'lucide-react-native';
import type { Category } from '../@types/category';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Emergência',
    icon: Siren,
    subs: [],
  },
  {
    id: '2',
    name: 'Casa e manutenção',
    icon: House,
    subs: [
      { id: '2-1', name: 'Pintor', icon: Paintbrush },
      { id: '2-2', name: 'Pedreiro', icon: BrickWall },
      { id: '2-3', name: 'Gesseiro', icon: Layers },
      { id: '2-4', name: 'Vidraceiro', icon: PanelTop },
      { id: '2-5', name: 'Jardinagem', icon: Flower2 },
      { id: '2-6', name: 'Dedetização', icon: Bug },
    ],
  },
  {
    id: '3',
    name: 'Tecnologia',
    icon: Monitor,
    subs: [
      { id: '3-1', name: 'Assistência celular', icon: Smartphone },
      { id: '3-2', name: 'Conserto de computador', icon: Laptop },
      { id: '3-3', name: 'Instalação de internet', icon: Wifi },
    ],
  },
  {
    id: '4',
    name: 'Beleza e bem-estar',
    icon: Scissors,
    subs: [
      { id: '4-1', name: 'Manicure/Pedicure', icon: Hand },
      { id: '4-2', name: 'Cabeleireiro', icon: Scissors },
      { id: '4-3', name: 'Maquiagem', icon: Palette },
      { id: '4-4', name: 'Massagem', icon: Heart },
    ],
  },
  {
    id: '5',
    name: 'Aulas e educação',
    icon: GraduationCap,
    subs: [
      { id: '5-1', name: 'Reforço escolar', icon: BookOpen },
      { id: '5-2', name: 'Inglês particular', icon: Languages },
      { id: '5-3', name: 'Música', icon: Music },
      { id: '5-4', name: 'Personal trainer', icon: Dumbbell },
    ],
  },
  {
    id: '6',
    name: 'Automotivo',
    icon: Car,
    subs: [
      { id: '6-1', name: 'Mecânico', icon: Wrench },
      { id: '6-2', name: 'Guincho', icon: Truck },
      { id: '6-3', name: 'Lava-jato delivery', icon: Droplets },
      { id: '6-4', name: 'Troca de bateria', icon: BatteryCharging },
    ],
  },
  {
    id: '7',
    name: 'Eventos',
    icon: PartyPopper,
    subs: [
      { id: '7-1', name: 'Fotógrafo', icon: Camera },
      { id: '7-2', name: 'DJ', icon: Disc3 },
      { id: '7-3', name: 'Buffet', icon: UtensilsCrossed },
      { id: '7-4', name: 'Decoração', icon: Gift },
    ],
  },
];
